package com.healthcare.healthcare.medico.entity;

public enum Especialidad {
    CARDIOLOGIA,DERMATOLOGIA,GASTROENTEROLOGIA,NEUROLOGIA,OFTALMOLOGIA,ENDOCRINOLOGIA,PEDIATRIA,
    GINECOLOGIA_Y_OBSTETRICIA,CIRUGIA_GENERAL,ONCOLOGIA,ORTOPEDIA,OTORRINOLARINGOLOGIA,PSIQUIATRIA,
    NEFROLOGIA,REUMATOLOGIA,ANESTESIOLOGIA,MEDICINA_INTERNA,RADIOLOGIA
}
