package com.healthcare.healthcare.medico.entity;

public enum Especialidad {
    CARDIOLOGIA,DERMATOLOGIA,GASTROENTEROLOGIA,NEUROLOGIA,OFTALMOLOGIA,ENDOCRINOLOGIA,PEDIATRIA,
    GINECOLOGIA_Y_OBSTETRICIA,ONCOLOGIA,ORTOPEDIA,OTORRINOLARINGOLOGIA,PSIQUIATRIA,
    NEFROLOGIA,REUMATOLOGIA,CONSULTA_GENERAL
}
